### ISSUE TITLE
Table tag not working custom block

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#100]
I have want table in custom block but it not working this is my code below

import { IBlock, IBlockData, BasicType, components } from 'easy-email-core';
import { CustomBlocksType } from '../constants';
import { Table} from '@arco-design/web-react';
import React from 'react';
import { merge } from 'lodash';
const {Section, Column,Text} = components;
const columns = [
    {
      title: 'ShortCodes',
      dataIndex: 'shortcodes',
    },
    {
      title: 'Description',
      dataIndex: 'description',
    }
];
const customer_details = [
    {
      key: '1',
      shortcodes: '{{customer.name}}',
      description: 'To get customer name',
    },
    {
      key: '2',
      shortcodes: '{{customer.email}}',
      description: 'To get customer E-Mail',
    },
    {
      key: '3',
      shortcodes: '{{customer.note}}',
      description: 'To get customer Note',
    },
    
];
export type IOrderDetailBlock = IBlockData<
{},
{}
>;
export const OrderDetail: IBlock = {
    name: 'Order Detail',
    type: CustomBlocksType.OrderDetail,
    create(payload){
        const defaultData: IOrderDetailBlock = {
            type: CustomBlocksType.OrderDetail,
            data:{
                value:{}
            },
            attributes:{},
            children: [],
        }
        return merge(defaultData, payload);
    },
    validParentType:[BasicType.SECTION],
    render(data:IOrderDetailBlock){
        //const {product,quantity,price} = data.data.value;
        const instance = (
            <Section>
                <Table 
                    columns ={columns}
                    data={customer_details}
                    pagination={false}
                    border={{ wrapper: true, cell: true }}
                />
            </Section>
        );
        return instance;
    }
}

**Comment by m-Ryan** [comment]
Please note that you can only use the jsx component from `components`.



```tsx
const {Section, Column,Text, Table} = components;
<Table>
  {`
  <tr style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <th style="padding: 0 15px 0 0;">Year</th>
    <th style="padding: 0 15px;">Language</th>
    <th style="padding: 0 0 0 15px;">Inspired from</th>
  </tr>
  <tr  style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <td style="padding: 0 15px 0 0;">1995</td>
    <td style="padding: 0 15px;">PHP</td>
    <td style="padding: 0 0 0 15px;">C, Shell Unix</td>
  </tr>
  <tr  style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <td style="padding: 0 15px 0 0;">1995</td>
    <td style="padding: 0 15px;">JavaScript</td>
    <td style="padding: 0 0 0 15px;">Scheme, Self</td>
  </tr>
  `}
</Table>

```

**Comment by Hateeb** [comment]
Thanks for such help
