### ISSUE TITLE
Ali mailbox mail style problem

### ISSUE THREAD

**Issue by wang1xiang** [arco-design/easy-email#101]
Figure 2 is the email template configured by the project, and Figure 1 is the email received by Ali mailbox. It was found that there was a problem with the style.
![邮箱](https://user-images.githubusercontent.com/37827912/158550376-e38dc871-67d8-4417-8692-f10cb8e4cb31.jpg)
![模板](https://user-images.githubusercontent.com/37827912/158550407-1fa732d8-9e0a-4e09-882f-9d1cc92a449a.jpg)

**Comment by m-Ryan** [comment]
Easy email is based on [MJML](https://github.com/mjmlio/mjml) , for all compatibility related issues, please go to [MJML](https://github.com/mjmlio/mjml) to submit a ticket.
