### ISSUE TITLE
Compiled once and deploy anywhere

### ISSUE THREAD

**Issue by xfinitysoft** [arco-design/easy-email#109]
We are facing some issues when we deploy compiled files on live sites.
When we deploy compiled files on abc.com it works fine.
The issue is started when we deploy files on subdomain.abc.com

Can you please let us know how we can compile the code once and deploy it on any domain without setting its absolute path?
Looking forward to hearing from you soon.

P.S: If we build just one file then its size is very big, so compiling the code into one file is not a solution.

We are looking forward to hearing from you soon.
Thank You

**Comment by m-Ryan** [comment]
`The issue is started when we deploy files on subdomain.abc.com`
What exactly is the problem ？It would be better to provide the error that occurred.

**Comment by xfinitysoft** [comment]
Thank You Ryan for your support.

We have tried and resolved the issue on our end.
We have a new issue that we need your help with and we are going to close this one and open another.

Thank You
