### ISSUE TITLE
Question: external dependencies

### ISSUE THREAD

**Issue by Volmarg** [arco-design/easy-email#110]
Hello,

Is this project relying on some externally fetched data like:
- images,
- iframes,
- api?

Literally anything? I keep searching for email builder that does not wrap things into one big iframe or contacts external api to work. Is this full "self-hosted", not relying on anything from outside?

**Comment by Volmarg** [comment]
Actually I found out quickly that it does rely on external services:
- qiniu.com

![image](https://user-images.githubusercontent.com/37488679/167242948-6c0df157-cab6-478b-9cb4-eaafe542a200.png)

Which handles the files upload.

Would that be possible for You to list the known cases where such cases as that are present?

**Comment by m-Ryan** [comment]
Not have any external services. This is just an example and you need to use your backend service to upload images.

https://github.com/arco-design/easy-email/blob/master/demo/src/pages/Editor/index.tsx#L133-L141

**Comment by Volmarg** [comment]
Great.

That solves it then. Thx.
