### ISSUE TITLE
How to Customize / Disable Merge Tag 

### ISSUE THREAD

**Issue by xfinitysoft** [arco-design/easy-email#111]
Hi Ryan 

We want to completely Disable/Hide Merge tag option from everywhere in the editor.
Please see the screenshot: https://i.imgur.com/tydNaSO.png

1 - How we can Disable/Hide it?
2 - How we can customize Merge Tag to add more options to it?

Looking forward to your quick support.
Thank You

**Comment by m-Ryan** [comment]
1. Hide Merge tag option if no merge tag props
![image](https://user-images.githubusercontent.com/20615214/168481635-85a76eb6-6676-457d-be4f-b1d8b6b88c03.png)
2. Merge tag is an object.
https://github.com/arco-design/easy-email/blob/master/demo/src/pages/Editor/testMergeTags.ts
