### ISSUE TITLE
Performance Issue - freezing browser tab

### ISSUE THREAD

**Issue by Volmarg** [arco-design/easy-email#112]
Hello,

**Problem:** opening / loading multiple iframe with the link to editor (using bit changed demo layout) literally freezes the browser tab. Tried with "firefox / chrome".

**How to recreate**:
- create empty html,
- add 3-5 iframes pointing to `email edit` page,
- watch the tab freezing,

**More as a question, maybe You are aware of the issue and have some idea where to start investigating it since I'll have to fix this somehow anyway?**

That's not related to my project specifically as I've made a test with new blank html file.

For example:
- having 20+ iframes pointing to `https://www.youtube.com/` works just fine (slow but still stable, no freezing issue), so that's also not an issue with my pc etc.

The thing is that I need to have at least 2 iframes on page, where the main one is used for editing / adding templates. I already had to delay the user interaction so that he won't close to fast current iframe and edit another template else tab is freezing as well.

**Comment by m-Ryan** [comment]
Pleasa send a full working exmaple.
