### ISSUE TITLE
Suggest adding a default / placeholder image when image block is inserted

### ISSUE THREAD

**Issue by zehawki** [arco-design/easy-email#113]
When an image block is added to the page it does not show any indication that something happened, or that an image block has actually been inserted. This leads to poor UX since the user does not know whether anything did occur, does not know how to select the block to add his own image, etc.

I suggest adding a default / placeholder image when image block is inserted, so that it's clear, and the block can be selected.

Eg here, Ive inserted an image block as can be seen in the layout pane, but nothing shows up in the editor.

![image](https://user-images.githubusercontent.com/8095144/168464511-762c338d-0a2a-4720-ad1b-4131331b64eb.png)

**Comment by m-Ryan** [comment]
Thanks, This‘s a bug in development, not the latest version. It has been fixed now.
