### ISSUE TITLE
VisualEditor: Scrollbar

### ISSUE THREAD

**Issue by ste7-ui** [arco-design/easy-email#115]
Hi,
while visual editor content overflows, a scrollbar correctly appears.
![image](https://user-images.githubusercontent.com/63000088/170002190-f2c1e3d7-06dd-4def-8be3-cd405963912e.png)
In my application I customized my scrollbar through some _css_ rules, but having an element called `#shadow-root` inside the html tree, I can't access `.shadow-container` element through a _css selector_, so then I am unable to style the scrollbar.

Is there any chance for that scrollbar to be styled externally?

**Comment by m-Ryan** [comment]
Example here: https://github.com/arco-design/easy-email/blob/master/packages/easy-email-extensions/src/AttributePanel/AttributePanel.tsx
```
import {
  getShadowRoot,
} from 'easy-email-editor';

  const shadowRoot = getShadowRoot();
  
  {shadowRoot &&
    ReactDOM.createPortal(
            <style> {` `}</style>,
    shadowRoot as any
  )}

```

**Comment by ste7-ui** [comment]
It still seems quite an hack to me since I need to duplicate my style from a sass mixin and hardcode it in a `<style>` tag like that. Although I can obviously reach the goal in this way it brings some code smells in my context.  

Unfortunately I don't think there is any scalable, performance driven, way to inherit my scrollbar custom styles from the `shadowRoot` parent using _JS_. 

At the end if there is no other way feel free to close this issue.

Thanks for the quick response!
