### ISSUE TITLE
Color picker: Scrolling with container

### ISSUE THREAD

**Issue by ste7-ui** [arco-design/easy-email#117]
Hi,
in my context, while color picker is opened, and I scroll my app-container, it scrolls with the page:
![color-picker-scrolling-issues](https://user-images.githubusercontent.com/63000088/170005601-5dc7effc-e59c-4743-8b10-984b85651809.gif)

It seems to be due to the color picker to be appended straight to the body in order to act as a _popover_. 
![image](https://user-images.githubusercontent.com/63000088/170007713-ff7c22e6-3ee8-4c69-a2a5-963ec4d292cd.png)

But this may cause problems in many application: usually it is not the body the element scrolling, so then while a container scrolls, the body stays fixed, causing the popover staying fixed.

I am wondering if you can append the popover under the editor root element, not under the body. This should let the editor and the popover scroll only when itself actually has an overflow, solving the color picker issue.
Any other solution is obviously appreciated.

Thanks a lot, best regards

**Comment by m-Ryan** [comment]
> append the popover under the editor root element

It looks good, it can be fixed in the next version,

**Comment by ste7-ui** [comment]
> It looks good, it can be fixed in the next version,

Hi, any update on this?

**Comment by m-Ryan** [comment]
Fix this in the latest version. 
please update
```
yarn add easy-email-core@latest easy-email-editor@latest easy-email-extensions@latest
```
