### ISSUE TITLE
yarn  demo error 

### ISSUE THREAD

**Issue by chysxslt** [arco-design/easy-email#121]
$ yarn demo
yarn run v1.22.18
$ cd demo && yarn build
$ vite build --config vite.production.config.ts
vite v2.6.14 building for production...
✓ 51 modules transformed.
[alias] Failed to resolve entry for package "D:\CodeTest\easy-email\packages\easy-email-editor". The package may have incorrect main/module/e
xports specified in its package.json: Failed to resolve entry for package "D:\CodeTest\easy-email\packages\easy-email-editor". The package ma
y have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "D:\CodeTest\easy-email\packages\easy-email-editor". The package may have incorrect main/module/ex
ports specified in its package.json: Failed to resolve entry for package "D:\CodeTest\easy-email\packages\easy-email-editor". The package may
 have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (D:\CodeTest\easy-email\demo\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:30273:11)
    at tryResolveFile (D:\CodeTest\easy-email\demo\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:29994:38)
    at tryFsResolve (D:\CodeTest\easy-email\demo\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:29976:16)
    at Object.resolveId (D:\CodeTest\easy-email\demo\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:29882:24)
    at D:\CodeTest\easy-email\demo\node_modules\rollup\dist\shared\rollup.js:22697:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chysxslt** [comment]
node  v18.3.0
yarn   v1.22.18
win10 
webstrom

**Comment by m-Ryan** [comment]
Can't reproduce, please try yarn dev to see if it works

**Comment by chysxslt** [comment]
I change @types/lodash's version to 4.14.181, its works.
