### ISSUE TITLE
Repositioning elements on the editor

### ISSUE THREAD

**Issue by shahiakriti** [arco-design/easy-email#123]
When trying to drag and move elements on the email editor to change the layout, it leaves behind columns and sections in the editor from where the element was dragged from. This leads to users having to delete the columns and sections multiple amount of time whenever a repositioning is done. 
Below is the example:

Before repositioning the elements:
![image](https://user-images.githubusercontent.com/99622173/173993676-7085f039-6657-4adc-8e28-b8c5cae1aadc.png)

After repositioning:
![image](https://user-images.githubusercontent.com/99622173/173993856-86ba726b-32a7-46c0-b5c8-42d932b52d58.png)

Here I moved the text block under the button and it left a column in the position where the text was earlier.

**Comment by m-Ryan** [comment]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/20615214/174017540-18ff4d4e-6a07-4559-80ef-f0fbbe7f7de3.png">

In this case, I don't think Section/Column should be used.
Text can be used as a stand-alone
