### ISSUE TITLE
Some suggested usability improvements

### ISSUE THREAD

**Issue by zehawki** [arco-design/easy-email#126]
1. The left toolbar is not being made full use of. Screens are wide with a lot of real estate, and it can easily accommodate 2 columns of buttons - thus having all the blocks on the toolbar itself, ie the first 2 columns of the popup can actually be accommodated on the ShortcutToolbar to provide:

- Easier access
- Discovery - let users know at a glance what all is available

2. The icons on the toolbar are non-intuitive. Eg Navbar looks like a list. Social is hard to understand, Etc. Icons should be accompanied with text. Conversely # 1 that I mentioned above will solve this automatically.
3. The popup allows dragging only for 3 of the top text blocks and none of the rest of text and other blocks. One has to carefully drag from the pull bar (6 dots). Would be good if the entire block is draggable.
4. The popup should not need explicit closing via button. Clicking outside should close the popup, as is usual.

For # 1 and # 2, I looked at https://github.com/arco-design/easy-email/blob/master/packages/easy-email-extensions/readme.md, but there do not seem to be any instructions on how to modify the ShortcutToolbar.

**Comment by m-Ryan** [comment]
https://github.com/arco-design/easy-email/issues/66
Easily customize the layout when you need it.

And we will consider adjusting the layout if someone is willing to provide a design draft.
