### ISSUE TITLE
Layout hide/show button bug

### ISSUE THREAD

**Issue by programmingtubetools** [arco-design/easy-email#130]
There's an issue to layout hide/show button, as it only hides layout. But does show it back it stuck in **"arco-card-grid:nth-child(1)"**.
![0](https://user-images.githubusercontent.com/67320795/178483112-69c34a60-abd5-45fc-83e5-ba9c1128be7d.png)

**Comment by m-Ryan** [comment]
Thanks. Please update 

```
yarn add easy-email-extensions
```
