### ISSUE TITLE
Couldn't drag and drop custom block

### ISSUE THREAD

**Issue by sarathjasrin** [arco-design/easy-email#137]
I have created a test custom block. It's showing in the categories but couldn't drag and drop.

```
import React from 'react'
import {BasicType, BlockManager, createCustomBlock, JsonToMjml, AdvancedType} from 'easy-email-core';
import {IPage} from "easy-email-core/lib/blocks";
import {CUSTOMBLOCKS} from '../../enums';
import {ProductBlock} from '../../../typings/product';
import {merge} from 'lodash';

const ProductsBlock = createCustomBlock({
    name: "Examinatr Products",
    type: CUSTOMBLOCKS.PRODUCTSBLOCK,
    create: (payload) => {
        const defaultData: ProductBlock = {
            type: CUSTOMBLOCKS.PRODUCTSBLOCK,
            data: {
                value: {
                    products: [
                        {
                            name: "Product Name",
                            description: "Cras risus ipsum, faucibus ut, ullamcorper id, varius ac, leo.",
                            image: "string",
                            link: new URL("/","http://localhost:3000/"),
                        }
                    ]
                }
            },
            attributes: {},
            children: []
        }
        return merge(payload, defaultData)
    },
    validParentType: [BasicType.SECTION, BasicType.PAGE, BasicType.WRAPPER,AdvancedType.WRAPPER],
    render: (params: {
        data: ProductBlock,
        idx?: string | null,
        mode: 'testing' | 'production',
        context?: IPage;
        dataSource?: {
            [key: string]: any;
        }
    }) => <div><h1>Product Gallery</h1></div>
});

function init() {
    BlockManager.registerBlocks({[CUSTOMBLOCKS.PRODUCTSBLOCK]:ProductsBlock});
    const pageBlock=BlockManager.getBlockByType(BasicType.PAGE);
    if(pageBlock){
        console.log(
            JsonToMjml({
                data:pageBlock.create({
                    children:[ProductsBlock.create()]
                }),
                mode:"production"
            })
        );
    }
}
export default init;
```

I have registered in left bar

```
import { BlockManager,BasicType } from 'easy-email-core';
import { BlockAttributeConfigurationManager, BlockMarketManager, BlockMaskWrapper } from 'easy-email-extensions';
import React from 'react';
import { CustomBlocksType } from './constants';
import {ProductsBlock,Panel as PPanel} from './ProductsBlock'

// BlockManager.registerBlocks({ MyFirstBlock: MyFirstBlock });

ProductsBlock();
BlockAttributeConfigurationManager.add({
  [CustomBlocksType.PRODUCTSBLOCK]:PPanel
});

BlockMarketManager.addCategories([
  {
    title: 'Custom',
    name: 'Custom',
    blocks: [    
      {
        type: CustomBlocksType.PRODUCTSBLOCK,
        title: 'Products block',
        description: 'An custom block',
        component: () => (
            <BlockMaskWrapper
                type={CustomBlocksType.MY_FIRST_BLOCK as any}
                payload={{

                }}
            >
              <div style={{ position: 'relative' }}>
                <img src={'https://test-site.com/logo.png'} style={{ maxWidth: '100%' }} />
                <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', zIndex: 2 }} />
              </div>
            </BlockMaskWrapper>
        ),
        thumbnail:
            'https://test-site.com/logo.png',
      }
    ],
  }
]);
```

**Comment by m-Ryan** [comment]
Example see here https://github.com/arco-design/easy-email/blob/master/demo/src/pages/Editor/components/CustomBlocks/ProductRecommendation/index.tsx

You need to register the custom block first.

changes:
```
// BlockManager.registerBlocks({ MyFirstBlock: MyFirstBlock });
```
to
```
BlockManager.registerBlocks({[CUSTOMBLOCKS.PRODUCTSBLOCK]:ProductsBlock});
```

Check if registered

console.log(BlockManager.getBlocks());

![image](https://user-images.githubusercontent.com/20615214/182033376-ed5ad6a9-7ac8-46e5-958d-08b787c5d467.png)

**Comment by m-Ryan** [comment]
And then，you must use the standard components instead of `div`.

```tsx
import { components } from 'easy-email-core';
const { Column, Section, Wrapper, Text, Button, Image, Group } = components;
```

**Comment by sarathjasrin** [comment]
@m-Ryan Sorry for the delay. I did changed the Register block. And also used component as you suggested above. It's showing in left bar but when I drag and drop it's letting me to drop.

**Comment by m-Ryan** [comment]
Please send a full working example.

**Comment by Alessandro-rep** [comment]
-I am having the same issue:

import { BlockManager } from 'easy-email-core';
import { BlockAttributeConfigurationManager } from 'easy-email-extensions';
import { CustomBlocksType } from './constants';
import { Panel as BloccoTestPanel, BloccoTest } from './BloccoTest';

BlockManager.registerBlocks({
    [CustomBlocksType.BLOCCO_TEST]: BloccoTest
});

BlockAttributeConfigurationManager.add({
    [CustomBlocksType.BLOCCO_TEST]: BloccoTestPanel
});

-With my Block declared here:

import {AdvancedType, BasicType, IBlockData, components, createCustomBlock } from "easy-email-core";
import mergeBlock from "../mergeBlock"
import { CustomBlocksType } from "../constants";
import React from "react";

const { Column, Section, Wrapper, Text } = components;

export type IBloccoTest = IBlockData<
    {
        'background-color': string;
        'title-color': string;
    },
    {
        title: string;
    }
>;

export const BloccoTest = createCustomBlock<IBloccoTest>({
    name: 'Blocco test',
    type: CustomBlocksType.BLOCCO_TEST,
    validParentType: [BasicType.PAGE, AdvancedType.WRAPPER, BasicType.WRAPPER],
    create: payload => {
        const defaultData: IBloccoTest = {
            type: CustomBlocksType.BLOCCO_TEST,
            data: {
                value: {
                    title: 'Blocco Test',
                },
            },
            attributes: {
                'background-color': '#ffffff',
                'title-color': '#222222',
            },
            children: [
                {
                    type: BasicType.TEXT,
                    children: [],
                    data: {
                        value: {
                            content: 'custom block title',
                        },
                    },
                    attributes: {},
                },
            ],
        };
        return mergeBlock(defaultData, payload);
    },
    render: ({ data, idx, mode, context, dataSource }) => {
        const { title } = data.data.value;
        const attributes = data.attributes;

        return(
            <Wrapper
                background-color={attributes['background-color']}>
                <Section>
                    <Column>
                         <Text
                             color={attributes['title-color']}>
                             {title}
                         </Text>
                    </Column>
                </Section>
            </Wrapper>
        )
    }
})

export { Panel } from './Panel';


-Is just a simple test to understand how all works, my block is displayed in the left panel, but when i try to drag and drop, it can't be inserted in the page, it doesn't interact with it at all.
Doing console.log(BlockManager.getBlocks()); i don't see my block in the list so i am guessing the problem is with the registration of the block but i think i did all the right steps, so i don't get where is the error.
I have all the files like in the examples and it compiles with no errors.
