### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by dmitry-osin** [arco-design/easy-email#143]
Hello @m-Ryan, during the easy email learning process I accidentally uploaded file with private information to your cloudinary cloud. Could you please clarify can I remove this file without disturbing you? I tried to find solution but looks like to call remove method I need to provide api key.

Thank you

**Comment by m-Ryan** [comment]
Please provide file links and I will delete it. You can send an email to me.

**Comment by dmitry-osin** [comment]
I sent the link on 962491243@qq.com. Thank you

**Comment by m-Ryan** [comment]
Done. Please check. @dmitry-osin

**Comment by dmitry-osin** [comment]
@m-Ryan it is still available by link that I've shared with you via email

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/187658860-61a13ac5-e465-4e60-a989-b4d72cab1861.png)

It may be due to cache, you can use incognito mode to check.

**Comment by dmitry-osin** [comment]
Yes, looks like it has been cached by chrome. Thank you 🙏
