### ISSUE TITLE
error on build application

### ISSUE THREAD

**Issue by shalb2018** [arco-design/easy-email#29]
Hi,
I started all over to install easy-email, installation went fine, but on npm run build, I get this error:

![easy email](https://user-images.githubusercontent.com/43252756/144218689-136ea427-0d37-4c66-ada9-9a55fa1bc4e9.jpg)

**Comment by m-Ryan** [comment]
Remove `!` if not use Typescript.

**Comment by shalb2018** [comment]
Hi,
thank you for the hint, that helped. When running build again, there came the next error: Cannot find module: 'react-final-form'. Make sure this package is installed.
I resolved that by installing react-final-form.
Build succeeded.

When starting easy-email, the window opens, but still (comparing to your demo) missing some things:

1. It does right away open with the editor, not with the demo templates. Do I have to install something more?
2. In the editor the header-part with export, send test mail and save is missing. How can I get that?

My editor window:
![easy-email-start](https://user-images.githubusercontent.com/43252756/144222012-766b5af7-6ea6-4f49-a3c4-87fae8dd942c.jpg)

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/144224686-0b9a7eb8-8f82-4ad0-8e6a-4d350a3bde22.png)

1. Just put whatever the default template you want in `initialValue`. The content field is what displayed in the editor, so make sure you set the correct value.

![image](https://user-images.githubusercontent.com/20615214/144225199-f0820df6-b864-4995-9313-dc3e46aa2850.png)

2. You can customize the buttons and stuff here :)

**Comment by shalb2018** [comment]
Thank you for your help. But it does not work yet. Now I have the following error:

![easy email](https://user-images.githubusercontent.com/43252756/144271500-fc9f2d07-b889-4a28-a2e4-3ba41f0c3e8b.jpg)

**Comment by m-Ryan** [comment]
It seems to be a syntax error, please check your code. Here is a simple demo [https://github.com/m-Ryan/easy-email-demo]( https://github.com/m-Ryan/easy-email-demo)

**Comment by shalb2018** [comment]
ok, I sorted that out (i hope), but now, I get this:

./src/App.js
Attempted import error: 'IEmailTemplate' is not exported from 'easy-email-editor'.

**Comment by m-Ryan** [comment]
> ok, I sorted that out (i hope), but now, I get this:
> 
> ./src/App.js Attempted import error: 'IEmailTemplate' is not exported from 'easy-email-editor'.

Pleasa send a full working exmaple

**Comment by shalb2018** [comment]
Thank you for your attention. I appreciate that.

Here my App.js: 
[App.zip](https://github.com/arco-design/easy-email/files/7641498/App.zip)

**Comment by m-Ryan** [comment]
> Thank you for your attention. I appreciate that.
> 
> Here my App.js: [App.zip](https://github.com/arco-design/easy-email/files/7641498/App.zip)

I think you are just using JavaScript and don’t need typings, try this

[App.zip](https://github.com/arco-design/easy-email/files/7641772/App.zip)

**Comment by shalb2018** [comment]
Thank you a lot, now it works. I will see by comparing my file with yours, what are the differences. Perhaps I learn something.
