### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by zaslavskyv** [arco-design/easy-email#35]
What is the reason behind the `subTitle` field? It doesn't seem to be used anywhere except of https://github.com/arco-design/easy-email/blob/2beb6a9c1eab0bf74988a78c8591a3d4d5bf5a95/demo/src/pages/Editor/components/useEmailModal.tsx#L62 but this has no effect anyway because next line sets the `html` property.

**Comment by m-Ryan** [comment]
If the plain text version is not found, many spam checkers may mark it as spam. 
Like sendgrid, they will ask us to provide the text version. https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/mail
