### ISSUE TITLE
Email is not updated if user does not click outside of the text edit area

### ISSUE THREAD

**Issue by zaslavskyv** [arco-design/easy-email#36]
Steps to reproduce:

1. Open the [editor](https://easy-email-m-ryan.vercel.app/editor);
2. Place a text block;
3. Enter something in the text block but do not click anything;
4. Click the "Export html" button;
5. Notice that the copied html contains "Make it easy for everyone to compose emails!" and not the text you've entered.

**Comment by m-Ryan** [comment]
Will fix next version.

**Comment by m-Ryan** [comment]
fix this. Please update version . 
```sh
yarn add easy-email-editor@3.0.15 easy-email-extensions@3.0.15

```
