### ISSUE TITLE
Merge tags are being replaced in the link popup

### ISSUE THREAD

**Issue by zaslavskyv** [arco-design/easy-email#41]
Steps to reproduce:

1. Open the [editor](https://easy-email-m-ryan.vercel.app/editor);
2. Place a text block;
3. Highlight everything in the text block and click the link button;
4. Enter `{{product_list.0.url}}` in the link box and click "Apply";
5. Click the link button again;
6. Notice that the link box now contains `https://easy-email-m-ryan.vercel.app/%7B%7Bproduct_list.0.url%7D%7D` instead of the entered text.

**Comment by m-Ryan** [comment]
Fixed, please update easy-email-extensions@3.1.5 @zaslavskyv

**Comment by zaslavskyv** [comment]
Thank you so much!
