### ISSUE TITLE
Conflict in dependency

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#44]
https://i.imgur.com/0HFObhn.png

**Comment by Hateeb** [comment]
[eresolve-report.txt](https://github.com/arco-design/easy-email/files/7783505/eresolve-report.txt)
[2021-12-28T07_44_21_989Z-debug-0.log](https://github.com/arco-design/easy-email/files/7783508/2021-12-28T07_44_21_989Z-debug-0.log)

**Comment by m-Ryan** [comment]
Thank you! Please update to latest version. @Hateeb 
```sh
yarn add easy-email-core@latest easy-email-editor@latest easy-email-extensions@latest
```

**Comment by Hateeb** [comment]
Thanks issue has been resolved
