### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#46]
You have fix min-width 1400px in email builder. I have opened in small screen laptop but not responsive

**Comment by m-Ryan** [comment]
If screen width is less than 1400,px  there will be scrolling.

![image](https://user-images.githubusercontent.com/20615214/147847540-898251ea-fc5f-40d5-9cee-330616583a59.png)

**Comment by Hateeb** [comment]
But you do not scroll I will want to autofit in small screen not scroll

**Comment by m-Ryan** [comment]
Sorry, we will not support mobile.

**Comment by Hateeb** [comment]
With 1400 min-width, image section tooltip text is getting hidden:
check the screenshot: https://i.imgur.com/0Efz7TJ.png 

What files do we need to look at to handle the builder on small laptop screens?
kindly mention the efficient solution.

The image block is just an example, other blocks with longer tooltip text are also getting hide the text.

Thank You

**Comment by m-Ryan** [comment]
> With 1400 min-width, image section tooltip text is getting hidden: check the screenshot: https://i.imgur.com/0Efz7TJ.png
> 
> What files do we need to look at to handle the builder on small laptop screens? kindly mention the efficient solution.
> 
> The image block is just an example, other blocks with longer tooltip text are also getting hide the text.
> 
> Thank You

This's’ not expected,  I will solve it in the next version.

**Comment by m-Ryan** [comment]
Please update to easy-email-extensions@3.1.27
Detail see https://github.com/arco-design/easy-email/pull/47/commits/3e3f7ed6dd10bcc77662b14c85cc0b8dcd69b6e0

**Comment by AlexandrDobrovolskiy** [comment]
https://user-images.githubusercontent.com/23122290/148423634-d8815574-1176-4253-a0c4-f664125de03b.mov

seems like this broke some overflows

**Comment by m-Ryan** [comment]
This is expected, did that on purpose so the "tool bar" is not covered
