### ISSUE TITLE
数据未实时更新

### ISSUE THREAD

**Issue by wang1xiang** [arco-design/easy-email#48]
拖拽多个text文本，修改时会视图数据改变，但json数据不变的情况
![image](https://user-images.githubusercontent.com/37827912/148179395-4eb762b0-48c2-49c2-a590-d9f1f4235a65.png)

**Comment by m-Ryan** [comment]
已经修复了，可以再看一下。

```sh
yarn add easy-email-core@3.1.28 easy-email-editor@3.1.28 easy-email-extensions@3.1.28
```
