### ISSUE TITLE
Handlebars HTML-escaping

### ISSUE THREAD

**Issue by zaslavskyv** [arco-design/easy-email#50]
Is it possible to tweak some of the merge tags to insert the "triple-stash" symbol `{{{` instead of the "double-stash" `{{`? Triple stash is used by [Handlebars](https://handlebarsjs.com/guide/expressions.html#html-escaping) to insert raw HTML.

**Comment by m-Ryan** [comment]
https://github.com/arco-design/easy-email/blob/master/packages/easy-email-editor/src/components/Provider/PropsProvider/index.tsx#L52

Maybe you just need to this @zaslavskyv 
```tsx
<EmailEditorProvider
    ...
     mergeTagGenerate ={(m) => `{{{${m}}}}`}
    >
    ...
</EmailEditorProvider>

```
