### ISSUE TITLE
git clone git@github.com:arco-design/easy-email.git $ cd easy-email $ yarn install-all  报错

### ISSUE THREAD

**Issue by strawberry3269** [arco-design/easy-email#60]
error https://registry.yarnpkg.com/@types/lodash/-/lodash-4.14.177.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open '/Users/bytedance/Library/Caches/Yarn/v6/npm-@types-lodash-4.14.177-f70c0d19c30fab101cad46b52be60363c43c4578-integrity/node_modules/@types/lodash/fp/fromPairs.d.ts'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error https://registry.yarnpkg.com/@typescript-eslint/experimental-utils/-/experimental-utils-4.33.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/Users/bytedance/Library/Caches/Yarn/v6/npm-@typescript-eslint-experimental-utils-4.33.0-6f2a786a4209fa2222989e9380b5331b2810f7fd-integrity/node_modules/@typescript-eslint/experimental-utils/_ts3.4/dist/ts-eslint/Scope.d.ts'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[#####################################################################] 913/916lerna ERR! yarn exited 1 in 'easy-email-editor'
lerna ERR! yarn exited 1 in 'easy-email-editor'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.

**Comment by m-Ryan** [comment]
没有复现这个问题，可以尝试进入到每个包下面安装
```sh
cd packages/easy-email-editor && yarn --force
cd packages/easy-email-core && yarn --force
cd packages/easy-email-extensions && yarn --force
cd demo && yarn
```
