### ISSUE TITLE
preload template

### ISSUE THREAD

**Issue by Nilegfx** [arco-design/easy-email#62]
Hi team, 
Thanks for the amazing tool. I enjoy working with it. quite intuitive. 

Could you please give a hint how can I preload the `EmailEditorProvider` with a predefined template?

**Comment by Nilegfx** [comment]
I got it by tracing this value here https://github.com/arco-design/easy-email/blob/ab1e11a1fbee0d7238fa05529318dbfc5cdcafbe/demo/src/pages/Editor/index.tsx#L226 

thanks and sorry for bothering. I'll close the ticket

**Comment by Nilegfx** [comment]
Sorry, I opened this again as the documentation doesn't match the code for the on `onBeforePreview` method. in the docs it state that it will pas you the IPage as first parameter but actually it passes html string.

**Comment by m-Ryan** [comment]
Documentation has been updated, we now recommend processing data in custom blocks.


Here is the  interface.
```tsx

export interface IBlock<T extends IBlockData = IBlockData> {
  name: string;
  type: string;
  create: (payload?: RecursivePartial<T>) => T;
  validParentType: string[];
  render?: (
    data: T,
    idx: string | null,
    mode: 'testing' | 'production',
    context?: IPage,
    dataSource?: { [key: string]: any }
  ) => IBlockData | ReactElement | null;
}
```
