### ISSUE TITLE
可以帮忙解释一下这些provider里面的参数吗

### ISSUE THREAD

**Issue by strawberry3269** [arco-design/easy-email#63]
![image](https://user-images.githubusercontent.com/20631538/149446587-e00e3e1b-3008-4660-80f1-54e393fb3d76.png)
可以帮忙解释一下这些provider里面的参数吗？

**Comment by m-Ryan** [comment]
`BlocksProvider` 是用来处理 `focusIdx`,`initialized` 状态
`FocusBlockLayoutProvider` 是用来处理当前选择的node节点 以及坐标。 （这个部分大概率以后会废弃，不需要这么麻烦）
`HoverIdxProvider`  是用来处理 `hoverIdx`,`dragging` 状态
`PropsProvider` 接收用户传入的额外参数
`RecordProvider` 用来做历史记录undo/redo
`ScrollProvider` 用来记录滚动的高度，保证edit 和 preview 的高度是一致的

`EmailEditorProvider` 这个是用户层面可以接受到的，其它的provider 包裹在它的里面。
