### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#66]
How to hide or show extension Blocklayer https://i.imgur.com/9TgbiT3.png
Kindly provide the code for this commit :
https://github.com/m-Ryan/easy-email-demo/tree/f15b96b00f25f6cec267c389c1895dad987a70ef

**Comment by m-Ryan** [comment]
Please see https://github.com/m-Ryan/easy-email-demo/pull/11

**Comment by Hateeb** [comment]
Kindly check the screenshot :
https://i.imgur.com/lWhVPKK.png

If you don't understand anything, please let me know.

**Comment by m-Ryan** [comment]
https://github.com/m-Ryan/easy-email-demo/tree/issue/66/src/SimpleLayout

You can refer to here and modify it，it won't be hard.

**Comment by Hateeb** [comment]
Thanks
