### ISSUE TITLE
Curser position issue in input fields ( Attribute Panel )

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#68]
To highlight the issue, I have created a video for you, please take a look.
https://www.loom.com/share/af260077665045879acc5659c93ed92f

As soon as I edit the field, the cursor position is changed, and take the cursor at the end.

This issue exist on Nov 28 verified commit:
https://github.com/m-Ryan/easy-email-demo/tree/f15b96b00f25f6cec267c389c1895dad987a70ef

**Comment by m-Ryan** [comment]
Can not reproduce in `https://easy-email-demo.vercel.app/`, please check dependencies in package.json.

**Comment by m-Ryan** [comment]
Looks like a bug in `react-final-form`,  please update  "react-final-form": "^6.5.7",
