### ISSUE TITLE
Lot of inconsistencies in Demo and Main Repo 

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#69]
There is a verified commit for the demo version which also has a lot of inconsistencies and mistakes as compared to the main repo.

The verified commit is: https://github.com/m-Ryan/easy-email-demo/tree/f15b96b00f25f6cec267c389c1895dad987a70ef
The main repo I am referring to is: https://github.com/arco-design/easy-email

Kindly upload the latest code on the demo as well with a verified commit.

As some things are working on the main repo while some are not working on a demo.
Looking forward to your kind response.
Thank You

**Comment by m-Ryan** [comment]
Dependencies have been updated now. But what are the inconsistencies you said?
