### ISSUE TITLE
Increase number of products in recommended product block dynamically via API

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#70]
As you have 3 products in recommended product block: https://i.imgur.com/3rt0AGv.png

What I want to achieve is: increase the number of products in the editor:
https://i.imgur.com/P71HMfq.png

Kindly let me know the code to achieve this.
Thank You

**Comment by m-Ryan** [comment]
Demo updated, see [https://github.com/arco-design/easy-email/blob/master/demo/src/pages/Editor/components/CustomBlocks/ProductRecommendation/index.tsx](https://github.com/arco-design/easy-email/blob/master/demo/src/pages/Editor/components/CustomBlocks/ProductRecommendation/index.tsx)
