### ISSUE TITLE
Upload image from Localhost

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#73]
Hi,
Sorry for reopening this issue,
This issue is already mentioned in : https://github.com/arco-design/easy-email/issues/67

I tried my best to get the result of uploading the image on the server-side, I checked the code on the main repo of how you are doing it.

I am just lost in the code and could not get any help.
What I want to achieve is the following things:
1 - When we click on the Upload Image button, the Image is get uploaded to the server
2 - Replaced Image in the Editor
3 - Show loader on the Upload Image button
4 - Provide code in the form of an object that holds the image so I can pass it to the server to store it.

I think there should be a component that we can reuse for the mentioned functionality.

Kindly assist with me code that I can use.
Looking forward to seeing the code as soon as possible.

Just to let you know I have tried my best before requesting the issue.

Thank You

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/151097557-070c4ca5-bc22-49f5-b91f-df074d0a3b01.png)

1. Have you added `onUploadImage `？
2. You can use `ImageUploaderField ` to upload image.
 ```ts
  import { ImageUploaderField } from 'easy-email-extensions';
 ```

**Comment by Hateeb** [comment]
Yes, I have implemented both points.
I just got stuck.

Cant we just reuse the component and place axious code to save the image in the backend or kindly provide the component that can reuse to place the background in the editor?

Looking forward to seeing the code 
Thank You

**Comment by m-Ryan** [comment]
I can’t help you without seeing your implementation. Please create a minimum reproduction of your problem or comment code snippets.

**Comment by Hateeb** [comment]
I have uploaded the code on Gmail and shared the download link on the given email address:
m-ryan@foxmail.com

In the given screenshot, you can see the file path and line #:
https://i.imgur.com/zc5K4Ne.png

Here is I have added the attribute you have mentioned in the previous comment:
https://i.imgur.com/6ZefsCN.png

Kindly download the code and run it on your system, 
As soon as You try to upload Background Image, 
You will see an error in the console and What I want to do is:
Upload image on the server and update background image in the editor.
Like you are doing it in the editor.

Kindly check the code and provide the direction of how I can do it.
Looking forward to your quick response.

Do you use Skype or any form of source to communicate quickly?
Please provide.

Thank You

**Comment by m-Ryan** [comment]
[Easy Email demo.zip](https://github.com/arco-design/easy-email/files/7951843/Easy.Email.demo.zip)


I have updated the demo.
```sh
yarn dev
yarn server

```
and then upload image

**Comment by Hateeb** [comment]
Thanks for your help
