### ISSUE TITLE
Save button is missing in Demo 

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#74]
Kindly Add a save button code in the demo so I can reuse the code as it is to update and Edit the Email.

Kindly provide the code in the component form.
Thank you

**Comment by m-Ryan** [comment]
Please see https://github.com/arco-design/easy-email/blob/master/demo/src/pages/Editor/index.tsx

**Comment by Hateeb** [comment]
Hi Thank You for quick repsonse.

I have checked the code and what I see, is code is imported from other packages.
When I try to import the same file, that file is importing other files as well.

I tried to import that files as well, still, code is not working as per expectation like 
showing loader on save button and then show success toast at the end.

I think as it is react, if you can reference the code that I needed then I can extract the code from those files.
As it is a simple button what I expect is :
A simple on-call event should trigger on click and save the template in the backend and show the success notification as you are doing in the main repo.

Can you please reference the code I need or provide a simple component to reuse in the demo?
Looking forward to your kind response.
Thank You

**Comment by m-Ryan** [comment]
Detail: https://github.com/m-Ryan/easy-email-demo/blob/main/src/App.tsx
Preview:  https://easy-email-demo-m-ryan.vercel.app/

**Comment by Hateeb** [comment]
Code is missing in the demo, 
Kindly check the screenshot :
https://i.imgur.com/AXiRCko.png

**Comment by Hateeb** [comment]
Thanks for help
