### ISSUE TITLE
Increase number of products in recommended product block dynamically via API

### ISSUE THREAD

**Issue by Hateeb** [arco-design/easy-email#75]
The issue is being discussed in the last thread here :
https://github.com/arco-design/easy-email/issues/70

The code you have provided is working as it shud be, Thank You for your help.

Now What I wanted to achieve is on selection from the drop-down, the new product is get loaded in the editor:
Like Newest product, Trending Product, Featured product 
There will be a drop-down to select the product.
Kindly assist with the code, how can I do this.
Thank You

**Comment by Hateeb** [comment]
I think I have not explained the point very well that's why there is a delay in response.
Let me explain what I wanted to achieve.

As you have implemented the product increase and decrease functionality, 
I need to implement one more drop-down field below the product increase, decrease field. 
So I can show Filter products like Trending, Most Viewed, Recently Added.

This kind of filter to filters the product from the backend.

As there could be thousands of products in the backend.
Just wanted to show the user-selected product in the editor.

Please help with the code to solve the problem like you previously did.

Looking forward to your help.
Thank You

**Comment by m-Ryan** [comment]
Please see [easy-email-demo.zip](https://github.com/arco-design/easy-email/files/7991734/easy-email-demo.zip)

**Comment by Hateeb** [comment]
thanks for help
