### ISSUE TITLE
Differences between this repo and the one own by m-Ryan

### ISSUE THREAD

**Issue by acanimal** [arco-design/easy-email#78]
First, awesome job team!

I found the demo points to the code relate with the forked repo https://github.com/m-Ryan/easy-email so I would like to know the reason and the differences between the two source codes.

Thanks in advance

**Comment by m-Ryan** [comment]
Our development process is Git-Forking Workflow.
I'm developing new features on `m-Ryan/easy-email `, and I will push them to `arco-design//easy-email ` when they are stable.

**Comment by acanimal** [comment]
Thanks for clarifying
