### ISSUE TITLE
Text 的children无法使用html tag

### ISSUE THREAD

**Issue by strawberry3269** [arco-design/easy-email#80]
![image](https://user-images.githubusercontent.com/20631538/152933406-39dba5c4-6043-42cc-bb02-571f3b8c838a.png)
![image](https://user-images.githubusercontent.com/20631538/152933471-414630a7-c495-465c-a0ba-3eb4e4764f38.png)
![image](https://user-images.githubusercontent.com/20631538/152933509-876e31c9-a54f-4712-9e3a-eadef0bf321f.png)

**Comment by m-Ryan** [comment]
只接受 string 作为children，可以这么写
```tsx
  <Text>
      {`<span style="color:green;">${title}</span>`}
  </Text>

```

**Comment by strawberry3269** [comment]
您的邮件已收到， ~~~
