### ISSUE TITLE
Color picker doesn't work on Safari

### ISSUE THREAD

**Issue by timbrownls20** [arco-design/easy-email#82]
Tbe color picker doesn't apply it's changes to text on safari. It works on chrome. It seems like the selection isn't recognised

This is also an issue for bold, italics and so forth - all of which appear to haver the same route cause

**Comment by m-Ryan** [comment]
Will check later.

**Comment by m-Ryan** [comment]
We used shadow dom to isolate styles, but selection api is not widely supported. There are already proposals to support, and when they're done, we'll fix this issue.
Relatived: https://github.com/WICG/webcomponents/issues/79#issuecomment-988103206
