### ISSUE TITLE
mj-include 无法使用

### ISSUE THREAD

**Issue by strawberry3269** [arco-design/easy-email#85]

**Comment by m-Ryan** [comment]
对mjml来说 mj-include 也只是在服务端能使用。 easy-email没有实现 mj-include，为什么需要使用 mj-include？

**Comment by strawberry3269** [comment]
需要使用class 在class比较多的情况希望可以引入css file



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ryan ***@***.***&gt;
发送时间: 2022年2月10日 12:44
收件人: arco-design/easy-email ***@***.***&gt;
抄送: strawberry3269 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[arco-design/easy-email] mj-include 无法使用 (Issue #85)





 
对mjml来说 mj-include 也只是在服务端能使用。 easy-email没有实现 mj-include，为什么需要使用 mj-include？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by m-Ryan** [comment]
你不能用 mj-include 加入css file，css style 只能放到 headStyles
![image](https://user-images.githubusercontent.com/20615214/153372225-d0142a10-d332-4f11-9308-799f676c9198.png)
如果有共用的代码片段，直接当成JSX引入即可，没有需要 mj-include 的必要。

**Comment by strawberry3269** [comment]
head style会被所有的 template html共享



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ryan ***@***.***&gt;
发送时间: 2022年2月10日 16:58
收件人: arco-design/easy-email ***@***.***&gt;
抄送: strawberry3269 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[arco-design/easy-email] mj-include 无法使用 (Issue #85)

**Comment by m-Ryan** [comment]
1. 你可以这样做,
```tsx
<Raw>{`styleText`}</Raw>
```
但是放到body的style有兼容性问题，放到header则不会。 我的建议是 2

2. 如果不想所有template共享，可以在添加 custom block 后往 headStyles 添加 css， 移除此block的时候 移除 headStyles的css

**Comment by strawberry3269** [comment]
嗯嗯 谢谢 根据2的建议我想一下咋改哈&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ryan ***@***.***&gt;
发送时间: 2022年2月10日 17:49
收件人: arco-design/easy-email ***@***.***&gt;
抄送: strawberry3269 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[arco-design/easy-email] mj-include 无法使用 (Issue #85)
