### ISSUE TITLE
Mobile preview does not auto scroll to current view 

### ISSUE THREAD

**Issue by nos-joel** [arco-design/easy-email#92]
While editing and then switching to desktop view, the currently edited item is still displayed on the view. On the contrary, if you switch to mobile view, it will automatically display the top of the page. It would be a great enhancement if it would display what is being edited for both, desktop and mobile.

**Comment by m-Ryan** [comment]
We will add this to roadmap.

**Comment by m-Ryan** [comment]
Fix this in latest version.
