### ISSUE TITLE
***Urgent*** 'Raw' block not working as expected

### ISSUE THREAD

**Issue by ste7-ui** [arco-design/easy-email#96]
Hi,
using the latest version (@3.2.0) the `Raw` block is not available through `ShortcutToolbar` extension. Although I've added a specific category in my context, containing a component that renders a BasicType.RAW, and system renders it correctly, it still does not work as expected.
# Demonstration
Following `MJML` native documentation for [`<mj-raw>`](https://documentation.mjml.io/#mj-raw), I tryed to add a basic condition:
![image](https://user-images.githubusercontent.com/63000088/156156620-95f1b4f5-82e5-423e-b435-ca9c21744aa0.png)
![image](https://user-images.githubusercontent.com/63000088/156156709-2a679a98-e60d-42fe-83bd-1fc493d74a0e.png)
MJML source becomes:
```html
<mjml>
    <mj-head>

        <mj-html-attributes>
            <mj-html-attribute class="easy-email" multiple-attributes="false" attribute-name="text-color"
                text-color="#000000"></mj-html-attribute>
            <mj-html-attribute class="easy-email" multiple-attributes="false" attribute-name="font-family"
                font-family="lucida Grande,Verdana,Microsoft YaHei"></mj-html-attribute>
            <mj-html-attribute class="easy-email" multiple-attributes="false" attribute-name="font-size"
                font-size="14px"></mj-html-attribute>
            <mj-html-attribute class="easy-email" multiple-attributes="false" attribute-name="line-height"
                line-height="1.7"></mj-html-attribute>
            <mj-html-attribute class="easy-email" multiple-attributes="false" attribute-name="responsive"
                responsive="true"></mj-html-attribute>

        </mj-html-attributes>



        <mj-breakpoint width="480px" />
        <mj-attributes>

            <mj-all font-family="lucida Grande,Verdana,Microsoft YaHei" />
            <mj-text font-size="14px" />
            <mj-text color="#000000" />
            <mj-text line-height="1.7" />


        </mj-attributes>
    </mj-head>
    <mj-body background-color="#efeeea" width="600px" css-class="mjml-body">

        <mj-wrapper padding="20px 0px 20px 0px" border="none" direction="ltr" text-align="center">

            <mj-section padding="20px 0px 20px 0px" background-repeat="repeat" background-size="auto"
                background-position="top center" border="none" direction="ltr" text-align="center">

                <mj-column padding="0px 0px 0px 0px" border="none" vertical-align="top">

                    <mj-raw>
                        {% if "a" == "b" %}
                    </mj-raw>


                    <mj-text padding="10px 25px 10px 25px" align="left">
                        Make it easy for everyone to compose emails!
                    </mj-text>


                    <mj-raw>
                        {% endif %}
                    </mj-raw>

                </mj-column>

            </mj-section>

        </mj-wrapper>

    </mj-body>
</mjml>
```
which seems to be fine according to doc, but the text block in between is still rendered in preview and in html export also:
![image](https://user-images.githubusercontent.com/63000088/156157443-05fd5d20-8b9f-48e8-b79a-4fc7c32f4c03.png)
# Is MJML?
This obviously means native `mj-raw` might be the problem. In fact I also tryed reproducing the same example in `MJML` [live demo](https://mjml.io/try-it-live/_oSylep1Q).
From my perspective something is not working as expected, am I missing something? An issue really similar has been opened [here](https://github.com/mjmlio/mjml/issues/1265), but the proposed solution is not working even in the given example.
What I suggest is trying to downgrade mjml verison in your packages and verify if it does work. 
# Notice
Even your [example](https://easy-email-m-ryan.vercel.app/editor?id=640&userId=77) is not working.

Hope for a quick solution, best regards.

**Comment by m-Ryan** [comment]
```
but the text block in between is still rendered in preview and in html export
```
looks as expected.

 You should use in combination with template engine, like [mustache](https://github.com/janl/mustache.js/) 、 [liquidjs ](https://liquidjs.com/
)

**Comment by m-Ryan** [comment]
liquidjs demo see [https://github.com/m-Ryan/easy-email-demo/pull/12](here https://github.com/m-Ryan/easy-email-demo/pull/12)

**Comment by ste7-ui** [comment]
Thank you for the quick answer.
I understand, so then you're saying that `MJML` doesn't handle conditions or loops natively, and you still need an engine preprocessing template, isn't it?
## Notice
Thank you for the demo, I honestly prefer using mustache. Just for notice [Inspect](https://github.com/m-Ryan/easy-email-demo/pull/12) code gives 404.
