### ISSUE TITLE
InteractivePrompt scroll issues

### ISSUE THREAD

**Issue by ste7-ui** [arco-design/easy-email#97]
When editor is placed in a page which height overflows, the focus tooltip does not stay attached to its focused element. In fact it does scroll with page since it has  `position: fixed`.  
A solution may be to set its `position: absolute` and make its parent `position: relative` setting `left: 0` and `top: -$label-height`, but as I've seen this is not enough when the tooltip should be placed over the *preview bar* beacuse it is in another DOM and `z-index` does not apply.

![interactive-prompt](https://user-images.githubusercontent.com/63000088/156733624-d1a5019e-e8fb-475c-af29-d881775b8d02.gif)

Can you try to fix this?

Best regards

**Comment by m-Ryan** [comment]
This problem will not occur in the next version, you can preview it first. [https://easy-email-m-ryan.vercel.app/](https://easy-email-m-ryan.vercel.app/)

**Comment by ste7-ui** [comment]
Thanks a lot! When will it be released?

**Comment by m-Ryan** [comment]
It will take about a week, we need to do more testing work.

**Comment by ste7-ui** [comment]
Okay thanks a lot!
