### ISSUE TITLE
Context tool bar doesn't have a font-height function

### ISSUE THREAD

**Issue by timbrownls20** [arco-design/easy-email#98]
It looks like the line-height option in the toolbar is working as font height. People got confused about that and thought they couldn't change the font height

Could we consider renaming line-height to font-height and perhaps changing the icon

Attache screenshot to illustrate which toolbar element I mean

![lineheight](https://user-images.githubusercontent.com/20048601/157381449-ce479c77-f0ad-4970-bd22-3743cb4a6002.png)

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/157451380-b5d8baf7-223b-41cb-b74d-2a055b7be73e.png)
It will be revised in the next version. Actually it modifies the font size
